index_HTML:
    path: /
    controller: App\Controller\ControllerHtml::Index
    methods: GET

AddContato_API:
    path: /api/
    controller: App\Controller\ContatosController::NovoContato
    methods: POST

listarContato_API:
    path: /api/contatos/
    controller: App\Controller\ContatosController::buscarContatos
    methods: GET

listarUmContato_API:
    path: /api/contatos/{id}
    controller: App\Controller\ContatosController::buscarUmContato
    methods: GET

editarUmContato_API:
    path: /api/contatos/{id}
    controller: App\Controller\ContatosController::editarContato
    methods: PUT