index_HTML:
    path: /
    controller: App\Controller\ControllerTeste::Index
    methods: GET

AddContato_API:
    path: /api/
    controller: App\Controller\ContatosController::NovoContato
    methods: POST

listarContato_API:
    path: /api/listarContatos/
    controller: App\Controller\ContatosController::buscarContatos
    methods: GET