index_HTML:
    path: /
    controller: App\Controller\ControllerTeste::Index
    methods: GET
AddNumero_API:
    path: /api/
    controller: App\Controller\ContatosController::NovoContato
    methods: POST